name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # or your source branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: npn project setup
        run: npm run project-setup

      - name: npn install
        run: npm install

#      - name: npn init
#        run: npm init -y
#
#      - name: tailwind
#        run: npm install -D tailwindcss postcss autoprefixer

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

